apiVersion: autoscaling/v1
apiVersion: batch/v1
kind: CronJob
metadata:
  name: todoapp-health-cronjob
  namespace: mateapp
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox-cron-pinger
            image: ikulyk404/busyboxplus:curl
            command: ["sh", "-c", "curl -s http://cluster.local"]
            resources:
              requests:
                cpu: "10m"
                memory: "16Mi"
              limits:
                cpu: "50m"
                memory: "32Mi"
          restartPolicy: OnFailure
